export const GENRES = ["Epic/Adventure","Sci-Fi","Thriller/Suspense","Drama","Action","Comedy","Documentary"];

export const MOVIES = [
  {id:1,title:"Lord of the Rings: Fellowship of the Ring",year:2001,genre:"Epic/Adventure"},
  {id:2,title:"Lord of the Rings: The Two Towers",year:2002,genre:"Epic/Adventure"},
  {id:3,title:"Lord of the Rings: Return of the King",year:2003,genre:"Epic/Adventure"},
  {id:4,title:"The Hobbit Trilogy",year:2012,genre:"Epic/Adventure"},
  {id:5,title:"Chronicles of Narnia",year:2005,genre:"Epic/Adventure"},
  {id:6,title:"Indiana Jones: Raiders of the Lost Ark",year:1981,genre:"Epic/Adventure"},
  {id:7,title:"Indiana Jones: Temple of Doom",year:1984,genre:"Epic/Adventure"},
  {id:8,title:"The Princess Bride",year:1987,genre:"Epic/Adventure"},
  {id:9,title:"The Goonies",year:1985,genre:"Epic/Adventure"},
  {id:10,title:"National Treasure",year:2004,genre:"Epic/Adventure"},
  {id:56,title:"Up",year:2009,genre:"Epic/Adventure"},
  {id:11,title:"E.T.",year:1982,genre:"Sci-Fi"},
  {id:12,title:"Close Encounters of the Third Kind",year:1977,genre:"Sci-Fi"},
  {id:13,title:"The Martian",year:2015,genre:"Sci-Fi"},
  {id:14,title:"Apollo 13",year:1995,genre:"Sci-Fi"},
  {id:15,title:"Jurassic Park",year:1993,genre:"Sci-Fi"},
  {id:16,title:"Project Hail Mary",year:2026,genre:"Sci-Fi"},
  {id:17,title:"Arrival",year:2016,genre:"Sci-Fi"},
  {id:18,title:"Interstellar",year:2014,genre:"Sci-Fi"},
  {id:19,title:"The Matrix",year:1999,genre:"Sci-Fi"},
  {id:57,title:"WALL-E",year:2008,genre:"Sci-Fi"},
  {id:58,title:"The Iron Giant",year:1999,genre:"Sci-Fi"},
  {id:20,title:"Gone Girl",year:2014,genre:"Thriller/Suspense"},
  {id:21,title:"Prisoners",year:2013,genre:"Thriller/Suspense"},
  {id:22,title:"Knives Out",year:2019,genre:"Thriller/Suspense"},
  {id:23,title:"Se7en",year:1995,genre:"Thriller/Suspense"},
  {id:24,title:"Zodiac",year:2007,genre:"Thriller/Suspense"},
  {id:25,title:"No Country for Old Men",year:2007,genre:"Thriller/Suspense"},
  {id:26,title:"Catch Me If You Can",year:2002,genre:"Thriller/Suspense"},
  {id:27,title:"Shawshank Redemption",year:1994,genre:"Drama"},
  {id:28,title:"Schindler's List",year:1993,genre:"Drama"},
  {id:29,title:"12 Angry Men",year:1957,genre:"Drama"},
  {id:30,title:"A Beautiful Mind",year:2001,genre:"Drama"},
  {id:31,title:"The Social Network",year:2010,genre:"Drama"},
  {id:32,title:"Spotlight",year:2015,genre:"Drama"},
  {id:33,title:"Whiplash",year:2014,genre:"Drama"},
  {id:34,title:"Rudy",year:1993,genre:"Drama"},
  {id:35,title:"Hoosiers",year:1986,genre:"Drama"},
  {id:36,title:"October Sky",year:1999,genre:"Drama"},
  {id:37,title:"McFarland USA",year:2015,genre:"Drama"},
  {id:38,title:"Gladiator",year:2000,genre:"Action"},
  {id:39,title:"The Dark Knight",year:2008,genre:"Action"},
  {id:40,title:"Bourne Identity",year:2002,genre:"Action"},
  {id:41,title:"13 Hours",year:2016,genre:"Action"},
  {id:42,title:"Zero Dark Thirty",year:2012,genre:"Action"},
  {id:43,title:"Argo",year:2012,genre:"Action"},
  {id:44,title:"Captain Phillips",year:2013,genre:"Action"},
  {id:45,title:"Ford v Ferrari",year:2019,genre:"Action"},
  {id:46,title:"1917",year:2019,genre:"Action"},
  {id:47,title:"Edge of Tomorrow",year:2014,genre:"Action"},
  {id:48,title:"Game Night",year:2018,genre:"Comedy"},
  {id:49,title:"The Grand Budapest Hotel",year:2014,genre:"Comedy"},
  {id:50,title:"The Nice Guys",year:2016,genre:"Comedy"},
  {id:51,title:"The Sandlot",year:1993,genre:"Comedy"},
  {id:52,title:"Burn After Reading",year:2008,genre:"Comedy"},
  {id:53,title:"Free Solo",year:2018,genre:"Documentary"},
  {id:54,title:"The Last Dance",year:2020,genre:"Documentary"},
  {id:55,title:"The Alpinist",year:2021,genre:"Documentary"},
];

export const RATING_EMOJIS = ["","👎","🤞","🤙","👌","👍"];
export const RATING_COLORS = ["","#f87171","#fb923c","#fbbf24","#a3e635","#4ade80"];
export const BATCH_SIZE = 5;
